// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: t4mp.proto

#ifndef PROTOBUF_t4mp_2eproto__INCLUDED
#define PROTOBUF_t4mp_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class ConnectAck;
class ConnectAckDefaultTypeInternal;
extern ConnectAckDefaultTypeInternal _ConnectAck_default_instance_;
class Packet;
class PacketDefaultTypeInternal;
extern PacketDefaultTypeInternal _Packet_default_instance_;
class PlayerSnap;
class PlayerSnapDefaultTypeInternal;
extern PlayerSnapDefaultTypeInternal _PlayerSnap_default_instance_;
class ServerSnap;
class ServerSnapDefaultTypeInternal;
extern ServerSnapDefaultTypeInternal _ServerSnap_default_instance_;
class ServerSnap_PlayerData;
class ServerSnap_PlayerDataDefaultTypeInternal;
extern ServerSnap_PlayerDataDefaultTypeInternal _ServerSnap_PlayerData_default_instance_;
class ServerSnap_PlayerData_WeaponWheel;
class ServerSnap_PlayerData_WeaponWheelDefaultTypeInternal;
extern ServerSnap_PlayerData_WeaponWheelDefaultTypeInternal _ServerSnap_PlayerData_WeaponWheel_default_instance_;

namespace protobuf_t4mp_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_t4mp_2eproto

enum Packet_Type {
  Packet_Type_invalid = 0,
  Packet_Type_client_connect = 1,
  Packet_Type_server_snap = 2,
  Packet_Type_client_snap = 3,
  Packet_Type_Packet_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Packet_Type_Packet_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Packet_Type_IsValid(int value);
const Packet_Type Packet_Type_Type_MIN = Packet_Type_invalid;
const Packet_Type Packet_Type_Type_MAX = Packet_Type_client_snap;
const int Packet_Type_Type_ARRAYSIZE = Packet_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* Packet_Type_descriptor();
inline const ::std::string& Packet_Type_Name(Packet_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    Packet_Type_descriptor(), value);
}
inline bool Packet_Type_Parse(
    const ::std::string& name, Packet_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Packet_Type>(
    Packet_Type_descriptor(), name, value);
}
// ===================================================================

class Packet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Packet) */ {
 public:
  Packet();
  virtual ~Packet();

  Packet(const Packet& from);

  inline Packet& operator=(const Packet& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Packet(Packet&& from) noexcept
    : Packet() {
    *this = ::std::move(from);
  }

  inline Packet& operator=(Packet&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Packet& default_instance();

  static inline const Packet* internal_default_instance() {
    return reinterpret_cast<const Packet*>(
               &_Packet_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Packet* other);
  friend void swap(Packet& a, Packet& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Packet* New() const PROTOBUF_FINAL { return New(NULL); }

  Packet* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Packet& from);
  void MergeFrom(const Packet& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Packet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef Packet_Type Type;
  static const Type invalid =
    Packet_Type_invalid;
  static const Type client_connect =
    Packet_Type_client_connect;
  static const Type server_snap =
    Packet_Type_server_snap;
  static const Type client_snap =
    Packet_Type_client_snap;
  static inline bool Type_IsValid(int value) {
    return Packet_Type_IsValid(value);
  }
  static const Type Type_MIN =
    Packet_Type_Type_MIN;
  static const Type Type_MAX =
    Packet_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    Packet_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return Packet_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return Packet_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return Packet_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // .PlayerSnap player_snapshot = 2;
  bool has_player_snapshot() const;
  void clear_player_snapshot();
  static const int kPlayerSnapshotFieldNumber = 2;
  const ::PlayerSnap& player_snapshot() const;
  ::PlayerSnap* mutable_player_snapshot();
  ::PlayerSnap* release_player_snapshot();
  void set_allocated_player_snapshot(::PlayerSnap* player_snapshot);

  // .ServerSnap server_snapshot = 3;
  bool has_server_snapshot() const;
  void clear_server_snapshot();
  static const int kServerSnapshotFieldNumber = 3;
  const ::ServerSnap& server_snapshot() const;
  ::ServerSnap* mutable_server_snapshot();
  ::ServerSnap* release_server_snapshot();
  void set_allocated_server_snapshot(::ServerSnap* server_snapshot);

  // .ConnectAck connect_ack = 4;
  bool has_connect_ack() const;
  void clear_connect_ack();
  static const int kConnectAckFieldNumber = 4;
  const ::ConnectAck& connect_ack() const;
  ::ConnectAck* mutable_connect_ack();
  ::ConnectAck* release_connect_ack();
  void set_allocated_connect_ack(::ConnectAck* connect_ack);

  // .Packet.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::Packet_Type type() const;
  void set_type(::Packet_Type value);

  // @@protoc_insertion_point(class_scope:Packet)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::PlayerSnap* player_snapshot_;
  ::ServerSnap* server_snapshot_;
  ::ConnectAck* connect_ack_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_t4mp_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ConnectAck : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ConnectAck) */ {
 public:
  ConnectAck();
  virtual ~ConnectAck();

  ConnectAck(const ConnectAck& from);

  inline ConnectAck& operator=(const ConnectAck& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConnectAck(ConnectAck&& from) noexcept
    : ConnectAck() {
    *this = ::std::move(from);
  }

  inline ConnectAck& operator=(ConnectAck&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ConnectAck& default_instance();

  static inline const ConnectAck* internal_default_instance() {
    return reinterpret_cast<const ConnectAck*>(
               &_ConnectAck_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(ConnectAck* other);
  friend void swap(ConnectAck& a, ConnectAck& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConnectAck* New() const PROTOBUF_FINAL { return New(NULL); }

  ConnectAck* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ConnectAck& from);
  void MergeFrom(const ConnectAck& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ConnectAck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 index = 1;
  void clear_index();
  static const int kIndexFieldNumber = 1;
  ::google::protobuf::int32 index() const;
  void set_index(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ConnectAck)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 index_;
  mutable int _cached_size_;
  friend struct protobuf_t4mp_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PlayerSnap : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PlayerSnap) */ {
 public:
  PlayerSnap();
  virtual ~PlayerSnap();

  PlayerSnap(const PlayerSnap& from);

  inline PlayerSnap& operator=(const PlayerSnap& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PlayerSnap(PlayerSnap&& from) noexcept
    : PlayerSnap() {
    *this = ::std::move(from);
  }

  inline PlayerSnap& operator=(PlayerSnap&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerSnap& default_instance();

  static inline const PlayerSnap* internal_default_instance() {
    return reinterpret_cast<const PlayerSnap*>(
               &_PlayerSnap_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(PlayerSnap* other);
  friend void swap(PlayerSnap& a, PlayerSnap& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PlayerSnap* New() const PROTOBUF_FINAL { return New(NULL); }

  PlayerSnap* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PlayerSnap& from);
  void MergeFrom(const PlayerSnap& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PlayerSnap* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float X = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // float Y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // float Z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // float ViewX = 4;
  void clear_viewx();
  static const int kViewXFieldNumber = 4;
  float viewx() const;
  void set_viewx(float value);

  // float ViewY = 5;
  void clear_viewy();
  static const int kViewYFieldNumber = 5;
  float viewy() const;
  void set_viewy(float value);

  // bool Walk_forward = 6;
  void clear_walk_forward();
  static const int kWalkForwardFieldNumber = 6;
  bool walk_forward() const;
  void set_walk_forward(bool value);

  // bool Walk_backward = 7;
  void clear_walk_backward();
  static const int kWalkBackwardFieldNumber = 7;
  bool walk_backward() const;
  void set_walk_backward(bool value);

  // bool Walk_left = 8;
  void clear_walk_left();
  static const int kWalkLeftFieldNumber = 8;
  bool walk_left() const;
  void set_walk_left(bool value);

  // bool Walk_right = 9;
  void clear_walk_right();
  static const int kWalkRightFieldNumber = 9;
  bool walk_right() const;
  void set_walk_right(bool value);

  // bool Jump = 10;
  void clear_jump();
  static const int kJumpFieldNumber = 10;
  bool jump() const;
  void set_jump(bool value);

  // bool Crouch = 11;
  void clear_crouch();
  static const int kCrouchFieldNumber = 11;
  bool crouch() const;
  void set_crouch(bool value);

  // bool Fire = 12;
  void clear_fire();
  static const int kFireFieldNumber = 12;
  bool fire() const;
  void set_fire(bool value);

  // bool Fire_hold = 13;
  void clear_fire_hold();
  static const int kFireHoldFieldNumber = 13;
  bool fire_hold() const;
  void set_fire_hold(bool value);

  // float Fire_hold_time = 14;
  void clear_fire_hold_time();
  static const int kFireHoldTimeFieldNumber = 14;
  float fire_hold_time() const;
  void set_fire_hold_time(float value);

  // bool Fire_release = 15;
  void clear_fire_release();
  static const int kFireReleaseFieldNumber = 15;
  bool fire_release() const;
  void set_fire_release(bool value);

  // float Fire_release_time = 16;
  void clear_fire_release_time();
  static const int kFireReleaseTimeFieldNumber = 16;
  float fire_release_time() const;
  void set_fire_release_time(float value);

  // int32 Weapon_switch = 17;
  void clear_weapon_switch();
  static const int kWeaponSwitchFieldNumber = 17;
  ::google::protobuf::int32 weapon_switch() const;
  void set_weapon_switch(::google::protobuf::int32 value);

  // float Weapon_switch_time = 18;
  void clear_weapon_switch_time();
  static const int kWeaponSwitchTimeFieldNumber = 18;
  float weapon_switch_time() const;
  void set_weapon_switch_time(float value);

  // int32 Weapon_slot = 19;
  void clear_weapon_slot();
  static const int kWeaponSlotFieldNumber = 19;
  ::google::protobuf::int32 weapon_slot() const;
  void set_weapon_slot(::google::protobuf::int32 value);

  // int32 packet_sequence = 20;
  void clear_packet_sequence();
  static const int kPacketSequenceFieldNumber = 20;
  ::google::protobuf::int32 packet_sequence() const;
  void set_packet_sequence(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PlayerSnap)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  float z_;
  float viewx_;
  float viewy_;
  bool walk_forward_;
  bool walk_backward_;
  bool walk_left_;
  bool walk_right_;
  bool jump_;
  bool crouch_;
  bool fire_;
  bool fire_hold_;
  float fire_hold_time_;
  bool fire_release_;
  float fire_release_time_;
  ::google::protobuf::int32 weapon_switch_;
  float weapon_switch_time_;
  ::google::protobuf::int32 weapon_slot_;
  ::google::protobuf::int32 packet_sequence_;
  mutable int _cached_size_;
  friend struct protobuf_t4mp_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ServerSnap_PlayerData_WeaponWheel : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ServerSnap.PlayerData.WeaponWheel) */ {
 public:
  ServerSnap_PlayerData_WeaponWheel();
  virtual ~ServerSnap_PlayerData_WeaponWheel();

  ServerSnap_PlayerData_WeaponWheel(const ServerSnap_PlayerData_WeaponWheel& from);

  inline ServerSnap_PlayerData_WeaponWheel& operator=(const ServerSnap_PlayerData_WeaponWheel& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ServerSnap_PlayerData_WeaponWheel(ServerSnap_PlayerData_WeaponWheel&& from) noexcept
    : ServerSnap_PlayerData_WeaponWheel() {
    *this = ::std::move(from);
  }

  inline ServerSnap_PlayerData_WeaponWheel& operator=(ServerSnap_PlayerData_WeaponWheel&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerSnap_PlayerData_WeaponWheel& default_instance();

  static inline const ServerSnap_PlayerData_WeaponWheel* internal_default_instance() {
    return reinterpret_cast<const ServerSnap_PlayerData_WeaponWheel*>(
               &_ServerSnap_PlayerData_WeaponWheel_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(ServerSnap_PlayerData_WeaponWheel* other);
  friend void swap(ServerSnap_PlayerData_WeaponWheel& a, ServerSnap_PlayerData_WeaponWheel& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ServerSnap_PlayerData_WeaponWheel* New() const PROTOBUF_FINAL { return New(NULL); }

  ServerSnap_PlayerData_WeaponWheel* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ServerSnap_PlayerData_WeaponWheel& from);
  void MergeFrom(const ServerSnap_PlayerData_WeaponWheel& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ServerSnap_PlayerData_WeaponWheel* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 bow_Normal_Ammo = 3;
  void clear_bow_normal_ammo();
  static const int kBowNormalAmmoFieldNumber = 3;
  ::google::protobuf::int32 bow_normal_ammo() const;
  void set_bow_normal_ammo(::google::protobuf::int32 value);

  // int32 bow_Explosive_Ammo = 4;
  void clear_bow_explosive_ammo();
  static const int kBowExplosiveAmmoFieldNumber = 4;
  ::google::protobuf::int32 bow_explosive_ammo() const;
  void set_bow_explosive_ammo(::google::protobuf::int32 value);

  // bool bWarClub = 1;
  void clear_bwarclub();
  static const int kBWarClubFieldNumber = 1;
  bool bwarclub() const;
  void set_bwarclub(bool value);

  // bool bHas_Bow = 2;
  void clear_bhas_bow();
  static const int kBHasBowFieldNumber = 2;
  bool bhas_bow() const;
  void set_bhas_bow(bool value);

  // bool bHas_TekBow = 6;
  void clear_bhas_tekbow();
  static const int kBHasTekBowFieldNumber = 6;
  bool bhas_tekbow() const;
  void set_bhas_tekbow(bool value);

  // bool bHas_SpikeGrenade = 10;
  void clear_bhas_spikegrenade();
  static const int kBHasSpikeGrenadeFieldNumber = 10;
  bool bhas_spikegrenade() const;
  void set_bhas_spikegrenade(bool value);

  // int32 bow_Poison_Ammo = 5;
  void clear_bow_poison_ammo();
  static const int kBowPoisonAmmoFieldNumber = 5;
  ::google::protobuf::int32 bow_poison_ammo() const;
  void set_bow_poison_ammo(::google::protobuf::int32 value);

  // int32 TekBow_NormalAmmo = 7;
  void clear_tekbow_normalammo();
  static const int kTekBowNormalAmmoFieldNumber = 7;
  ::google::protobuf::int32 tekbow_normalammo() const;
  void set_tekbow_normalammo(::google::protobuf::int32 value);

  // int32 TekBow_ExplosiveAmmo = 8;
  void clear_tekbow_explosiveammo();
  static const int kTekBowExplosiveAmmoFieldNumber = 8;
  ::google::protobuf::int32 tekbow_explosiveammo() const;
  void set_tekbow_explosiveammo(::google::protobuf::int32 value);

  // int32 TekBow_PosionAmmo = 9;
  void clear_tekbow_posionammo();
  static const int kTekBowPosionAmmoFieldNumber = 9;
  ::google::protobuf::int32 tekbow_posionammo() const;
  void set_tekbow_posionammo(::google::protobuf::int32 value);

  // int32 SpikeGrenade_Ammo = 11;
  void clear_spikegrenade_ammo();
  static const int kSpikeGrenadeAmmoFieldNumber = 11;
  ::google::protobuf::int32 spikegrenade_ammo() const;
  void set_spikegrenade_ammo(::google::protobuf::int32 value);

  // int32 Pistol_Ammo = 13;
  void clear_pistol_ammo();
  static const int kPistolAmmoFieldNumber = 13;
  ::google::protobuf::int32 pistol_ammo() const;
  void set_pistol_ammo(::google::protobuf::int32 value);

  // int32 ShotGun_Ammo = 15;
  void clear_shotgun_ammo();
  static const int kShotGunAmmoFieldNumber = 15;
  ::google::protobuf::int32 shotgun_ammo() const;
  void set_shotgun_ammo(::google::protobuf::int32 value);

  // bool bHas_Pistol = 12;
  void clear_bhas_pistol();
  static const int kBHasPistolFieldNumber = 12;
  bool bhas_pistol() const;
  void set_bhas_pistol(bool value);

  // bool bHas_ShotGun = 14;
  void clear_bhas_shotgun();
  static const int kBHasShotGunFieldNumber = 14;
  bool bhas_shotgun() const;
  void set_bhas_shotgun(bool value);

  // bool bHas_Flecheete = 16;
  void clear_bhas_flecheete();
  static const int kBHasFlecheeteFieldNumber = 16;
  bool bhas_flecheete() const;
  void set_bhas_flecheete(bool value);

  // bool bHas_RocketLauncher = 19;
  void clear_bhas_rocketlauncher();
  static const int kBHasRocketLauncherFieldNumber = 19;
  bool bhas_rocketlauncher() const;
  void set_bhas_rocketlauncher(bool value);

  // int32 Fleechete_Ammo = 17;
  void clear_fleechete_ammo();
  static const int kFleecheteAmmoFieldNumber = 17;
  ::google::protobuf::int32 fleechete_ammo() const;
  void set_fleechete_ammo(::google::protobuf::int32 value);

  // int32 MiniGun_Ammo = 18;
  void clear_minigun_ammo();
  static const int kMiniGunAmmoFieldNumber = 18;
  ::google::protobuf::int32 minigun_ammo() const;
  void set_minigun_ammo(::google::protobuf::int32 value);

  // int32 Rocket_Ammo1 = 20;
  void clear_rocket_ammo1();
  static const int kRocketAmmo1FieldNumber = 20;
  ::google::protobuf::int32 rocket_ammo1() const;
  void set_rocket_ammo1(::google::protobuf::int32 value);

  // int32 Rocket_Ammo2 = 21;
  void clear_rocket_ammo2();
  static const int kRocketAmmo2FieldNumber = 21;
  ::google::protobuf::int32 rocket_ammo2() const;
  void set_rocket_ammo2(::google::protobuf::int32 value);

  // int32 Rocket_Ammo3 = 22;
  void clear_rocket_ammo3();
  static const int kRocketAmmo3FieldNumber = 22;
  ::google::protobuf::int32 rocket_ammo3() const;
  void set_rocket_ammo3(::google::protobuf::int32 value);

  // int32 Plasma_Ammo1 = 24;
  void clear_plasma_ammo1();
  static const int kPlasmaAmmo1FieldNumber = 24;
  ::google::protobuf::int32 plasma_ammo1() const;
  void set_plasma_ammo1(::google::protobuf::int32 value);

  // int32 Plasma_Ammo2 = 25;
  void clear_plasma_ammo2();
  static const int kPlasmaAmmo2FieldNumber = 25;
  ::google::protobuf::int32 plasma_ammo2() const;
  void set_plasma_ammo2(::google::protobuf::int32 value);

  // int32 Plasma_Ammo3 = 26;
  void clear_plasma_ammo3();
  static const int kPlasmaAmmo3FieldNumber = 26;
  ::google::protobuf::int32 plasma_ammo3() const;
  void set_plasma_ammo3(::google::protobuf::int32 value);

  // bool bHas_PlasmaCannon = 23;
  void clear_bhas_plasmacannon();
  static const int kBHasPlasmaCannonFieldNumber = 23;
  bool bhas_plasmacannon() const;
  void set_bhas_plasmacannon(bool value);

  // bool bHas_FlameThrower = 27;
  void clear_bhas_flamethrower();
  static const int kBHasFlameThrowerFieldNumber = 27;
  bool bhas_flamethrower() const;
  void set_bhas_flamethrower(bool value);

  // bool bHas_SpiderMine = 29;
  void clear_bhas_spidermine();
  static const int kBHasSpiderMineFieldNumber = 29;
  bool bhas_spidermine() const;
  void set_bhas_spidermine(bool value);

  // bool bHas_GravityGun = 31;
  void clear_bhas_gravitygun();
  static const int kBHasGravityGunFieldNumber = 31;
  bool bhas_gravitygun() const;
  void set_bhas_gravitygun(bool value);

  // int32 FlameThrower_Ammo = 28;
  void clear_flamethrower_ammo();
  static const int kFlameThrowerAmmoFieldNumber = 28;
  ::google::protobuf::int32 flamethrower_ammo() const;
  void set_flamethrower_ammo(::google::protobuf::int32 value);

  // int32 SpiderMine_Ammo = 30;
  void clear_spidermine_ammo();
  static const int kSpiderMineAmmoFieldNumber = 30;
  ::google::protobuf::int32 spidermine_ammo() const;
  void set_spidermine_ammo(::google::protobuf::int32 value);

  // int32 GravityGun_Ammo = 32;
  void clear_gravitygun_ammo();
  static const int kGravityGunAmmoFieldNumber = 32;
  ::google::protobuf::int32 gravitygun_ammo() const;
  void set_gravitygun_ammo(::google::protobuf::int32 value);

  // int32 GravityGun_Ammo2 = 33;
  void clear_gravitygun_ammo2();
  static const int kGravityGunAmmo2FieldNumber = 33;
  ::google::protobuf::int32 gravitygun_ammo2() const;
  void set_gravitygun_ammo2(::google::protobuf::int32 value);

  // int32 DarkMatter_Ammo = 35;
  void clear_darkmatter_ammo();
  static const int kDarkMatterAmmoFieldNumber = 35;
  ::google::protobuf::int32 darkmatter_ammo() const;
  void set_darkmatter_ammo(::google::protobuf::int32 value);

  // bool bHas_DarkMatter = 34;
  void clear_bhas_darkmatter();
  static const int kBHasDarkMatterFieldNumber = 34;
  bool bhas_darkmatter() const;
  void set_bhas_darkmatter(bool value);

  // bool bHas_CrossBow = 36;
  void clear_bhas_crossbow();
  static const int kBHasCrossBowFieldNumber = 36;
  bool bhas_crossbow() const;
  void set_bhas_crossbow(bool value);

  // int32 CrossBow_Normal_Ammo = 37;
  void clear_crossbow_normal_ammo();
  static const int kCrossBowNormalAmmoFieldNumber = 37;
  ::google::protobuf::int32 crossbow_normal_ammo() const;
  void set_crossbow_normal_ammo(::google::protobuf::int32 value);

  // int32 CrossBow_Explosive_Ammo = 38;
  void clear_crossbow_explosive_ammo();
  static const int kCrossBowExplosiveAmmoFieldNumber = 38;
  ::google::protobuf::int32 crossbow_explosive_ammo() const;
  void set_crossbow_explosive_ammo(::google::protobuf::int32 value);

  // int32 CrossBow_Poison_Ammo = 39;
  void clear_crossbow_poison_ammo();
  static const int kCrossBowPoisonAmmoFieldNumber = 39;
  ::google::protobuf::int32 crossbow_poison_ammo() const;
  void set_crossbow_poison_ammo(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ServerSnap.PlayerData.WeaponWheel)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 bow_normal_ammo_;
  ::google::protobuf::int32 bow_explosive_ammo_;
  bool bwarclub_;
  bool bhas_bow_;
  bool bhas_tekbow_;
  bool bhas_spikegrenade_;
  ::google::protobuf::int32 bow_poison_ammo_;
  ::google::protobuf::int32 tekbow_normalammo_;
  ::google::protobuf::int32 tekbow_explosiveammo_;
  ::google::protobuf::int32 tekbow_posionammo_;
  ::google::protobuf::int32 spikegrenade_ammo_;
  ::google::protobuf::int32 pistol_ammo_;
  ::google::protobuf::int32 shotgun_ammo_;
  bool bhas_pistol_;
  bool bhas_shotgun_;
  bool bhas_flecheete_;
  bool bhas_rocketlauncher_;
  ::google::protobuf::int32 fleechete_ammo_;
  ::google::protobuf::int32 minigun_ammo_;
  ::google::protobuf::int32 rocket_ammo1_;
  ::google::protobuf::int32 rocket_ammo2_;
  ::google::protobuf::int32 rocket_ammo3_;
  ::google::protobuf::int32 plasma_ammo1_;
  ::google::protobuf::int32 plasma_ammo2_;
  ::google::protobuf::int32 plasma_ammo3_;
  bool bhas_plasmacannon_;
  bool bhas_flamethrower_;
  bool bhas_spidermine_;
  bool bhas_gravitygun_;
  ::google::protobuf::int32 flamethrower_ammo_;
  ::google::protobuf::int32 spidermine_ammo_;
  ::google::protobuf::int32 gravitygun_ammo_;
  ::google::protobuf::int32 gravitygun_ammo2_;
  ::google::protobuf::int32 darkmatter_ammo_;
  bool bhas_darkmatter_;
  bool bhas_crossbow_;
  ::google::protobuf::int32 crossbow_normal_ammo_;
  ::google::protobuf::int32 crossbow_explosive_ammo_;
  ::google::protobuf::int32 crossbow_poison_ammo_;
  mutable int _cached_size_;
  friend struct protobuf_t4mp_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ServerSnap_PlayerData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ServerSnap.PlayerData) */ {
 public:
  ServerSnap_PlayerData();
  virtual ~ServerSnap_PlayerData();

  ServerSnap_PlayerData(const ServerSnap_PlayerData& from);

  inline ServerSnap_PlayerData& operator=(const ServerSnap_PlayerData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ServerSnap_PlayerData(ServerSnap_PlayerData&& from) noexcept
    : ServerSnap_PlayerData() {
    *this = ::std::move(from);
  }

  inline ServerSnap_PlayerData& operator=(ServerSnap_PlayerData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerSnap_PlayerData& default_instance();

  static inline const ServerSnap_PlayerData* internal_default_instance() {
    return reinterpret_cast<const ServerSnap_PlayerData*>(
               &_ServerSnap_PlayerData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(ServerSnap_PlayerData* other);
  friend void swap(ServerSnap_PlayerData& a, ServerSnap_PlayerData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ServerSnap_PlayerData* New() const PROTOBUF_FINAL { return New(NULL); }

  ServerSnap_PlayerData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ServerSnap_PlayerData& from);
  void MergeFrom(const ServerSnap_PlayerData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ServerSnap_PlayerData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef ServerSnap_PlayerData_WeaponWheel WeaponWheel;

  // accessors -------------------------------------------------------

  // .ServerSnap.PlayerData.WeaponWheel weapons = 22;
  bool has_weapons() const;
  void clear_weapons();
  static const int kWeaponsFieldNumber = 22;
  const ::ServerSnap_PlayerData_WeaponWheel& weapons() const;
  ::ServerSnap_PlayerData_WeaponWheel* mutable_weapons();
  ::ServerSnap_PlayerData_WeaponWheel* release_weapons();
  void set_allocated_weapons(::ServerSnap_PlayerData_WeaponWheel* weapons);

  // float X = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // float Y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // float Z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // float ViewX = 4;
  void clear_viewx();
  static const int kViewXFieldNumber = 4;
  float viewx() const;
  void set_viewx(float value);

  // float ViewY = 5;
  void clear_viewy();
  static const int kViewYFieldNumber = 5;
  float viewy() const;
  void set_viewy(float value);

  // bool Walk_forward = 6;
  void clear_walk_forward();
  static const int kWalkForwardFieldNumber = 6;
  bool walk_forward() const;
  void set_walk_forward(bool value);

  // bool Walk_backward = 7;
  void clear_walk_backward();
  static const int kWalkBackwardFieldNumber = 7;
  bool walk_backward() const;
  void set_walk_backward(bool value);

  // bool Walk_left = 8;
  void clear_walk_left();
  static const int kWalkLeftFieldNumber = 8;
  bool walk_left() const;
  void set_walk_left(bool value);

  // bool Walk_right = 9;
  void clear_walk_right();
  static const int kWalkRightFieldNumber = 9;
  bool walk_right() const;
  void set_walk_right(bool value);

  // bool Jump = 10;
  void clear_jump();
  static const int kJumpFieldNumber = 10;
  bool jump() const;
  void set_jump(bool value);

  // bool Crouch = 11;
  void clear_crouch();
  static const int kCrouchFieldNumber = 11;
  bool crouch() const;
  void set_crouch(bool value);

  // bool Fire = 12;
  void clear_fire();
  static const int kFireFieldNumber = 12;
  bool fire() const;
  void set_fire(bool value);

  // bool Fire_hold = 13;
  void clear_fire_hold();
  static const int kFireHoldFieldNumber = 13;
  bool fire_hold() const;
  void set_fire_hold(bool value);

  // float Fire_hold_time = 14;
  void clear_fire_hold_time();
  static const int kFireHoldTimeFieldNumber = 14;
  float fire_hold_time() const;
  void set_fire_hold_time(float value);

  // bool Fire_release = 15;
  void clear_fire_release();
  static const int kFireReleaseFieldNumber = 15;
  bool fire_release() const;
  void set_fire_release(bool value);

  // float Fire_release_time = 16;
  void clear_fire_release_time();
  static const int kFireReleaseTimeFieldNumber = 16;
  float fire_release_time() const;
  void set_fire_release_time(float value);

  // float Max_health = 17;
  void clear_max_health();
  static const int kMaxHealthFieldNumber = 17;
  float max_health() const;
  void set_max_health(float value);

  // float Current_health = 18;
  void clear_current_health();
  static const int kCurrentHealthFieldNumber = 18;
  float current_health() const;
  void set_current_health(float value);

  // int32 Weapon_switch = 19;
  void clear_weapon_switch();
  static const int kWeaponSwitchFieldNumber = 19;
  ::google::protobuf::int32 weapon_switch() const;
  void set_weapon_switch(::google::protobuf::int32 value);

  // float Weapon_switch_time = 20;
  void clear_weapon_switch_time();
  static const int kWeaponSwitchTimeFieldNumber = 20;
  float weapon_switch_time() const;
  void set_weapon_switch_time(float value);

  // int32 Weapon_slot = 21;
  void clear_weapon_slot();
  static const int kWeaponSlotFieldNumber = 21;
  ::google::protobuf::int32 weapon_slot() const;
  void set_weapon_slot(::google::protobuf::int32 value);

  // int32 index = 23;
  void clear_index();
  static const int kIndexFieldNumber = 23;
  ::google::protobuf::int32 index() const;
  void set_index(::google::protobuf::int32 value);

  // int32 death_type = 24;
  void clear_death_type();
  static const int kDeathTypeFieldNumber = 24;
  ::google::protobuf::int32 death_type() const;
  void set_death_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ServerSnap.PlayerData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::ServerSnap_PlayerData_WeaponWheel* weapons_;
  float x_;
  float y_;
  float z_;
  float viewx_;
  float viewy_;
  bool walk_forward_;
  bool walk_backward_;
  bool walk_left_;
  bool walk_right_;
  bool jump_;
  bool crouch_;
  bool fire_;
  bool fire_hold_;
  float fire_hold_time_;
  bool fire_release_;
  float fire_release_time_;
  float max_health_;
  float current_health_;
  ::google::protobuf::int32 weapon_switch_;
  float weapon_switch_time_;
  ::google::protobuf::int32 weapon_slot_;
  ::google::protobuf::int32 index_;
  ::google::protobuf::int32 death_type_;
  mutable int _cached_size_;
  friend struct protobuf_t4mp_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ServerSnap : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ServerSnap) */ {
 public:
  ServerSnap();
  virtual ~ServerSnap();

  ServerSnap(const ServerSnap& from);

  inline ServerSnap& operator=(const ServerSnap& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ServerSnap(ServerSnap&& from) noexcept
    : ServerSnap() {
    *this = ::std::move(from);
  }

  inline ServerSnap& operator=(ServerSnap&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerSnap& default_instance();

  static inline const ServerSnap* internal_default_instance() {
    return reinterpret_cast<const ServerSnap*>(
               &_ServerSnap_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(ServerSnap* other);
  friend void swap(ServerSnap& a, ServerSnap& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ServerSnap* New() const PROTOBUF_FINAL { return New(NULL); }

  ServerSnap* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ServerSnap& from);
  void MergeFrom(const ServerSnap& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ServerSnap* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef ServerSnap_PlayerData PlayerData;

  // accessors -------------------------------------------------------

  // repeated .ServerSnap.PlayerData player = 1;
  int player_size() const;
  void clear_player();
  static const int kPlayerFieldNumber = 1;
  const ::ServerSnap_PlayerData& player(int index) const;
  ::ServerSnap_PlayerData* mutable_player(int index);
  ::ServerSnap_PlayerData* add_player();
  ::google::protobuf::RepeatedPtrField< ::ServerSnap_PlayerData >*
      mutable_player();
  const ::google::protobuf::RepeatedPtrField< ::ServerSnap_PlayerData >&
      player() const;

  // int32 packet_sequence = 2;
  void clear_packet_sequence();
  static const int kPacketSequenceFieldNumber = 2;
  ::google::protobuf::int32 packet_sequence() const;
  void set_packet_sequence(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ServerSnap)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ServerSnap_PlayerData > player_;
  ::google::protobuf::int32 packet_sequence_;
  mutable int _cached_size_;
  friend struct protobuf_t4mp_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Packet

// .Packet.Type type = 1;
inline void Packet::clear_type() {
  type_ = 0;
}
inline ::Packet_Type Packet::type() const {
  // @@protoc_insertion_point(field_get:Packet.type)
  return static_cast< ::Packet_Type >(type_);
}
inline void Packet::set_type(::Packet_Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:Packet.type)
}

// .PlayerSnap player_snapshot = 2;
inline bool Packet::has_player_snapshot() const {
  return this != internal_default_instance() && player_snapshot_ != NULL;
}
inline void Packet::clear_player_snapshot() {
  if (GetArenaNoVirtual() == NULL && player_snapshot_ != NULL) delete player_snapshot_;
  player_snapshot_ = NULL;
}
inline const ::PlayerSnap& Packet::player_snapshot() const {
  const ::PlayerSnap* p = player_snapshot_;
  // @@protoc_insertion_point(field_get:Packet.player_snapshot)
  return p != NULL ? *p : *reinterpret_cast<const ::PlayerSnap*>(
      &::_PlayerSnap_default_instance_);
}
inline ::PlayerSnap* Packet::mutable_player_snapshot() {
  
  if (player_snapshot_ == NULL) {
    player_snapshot_ = new ::PlayerSnap;
  }
  // @@protoc_insertion_point(field_mutable:Packet.player_snapshot)
  return player_snapshot_;
}
inline ::PlayerSnap* Packet::release_player_snapshot() {
  // @@protoc_insertion_point(field_release:Packet.player_snapshot)
  
  ::PlayerSnap* temp = player_snapshot_;
  player_snapshot_ = NULL;
  return temp;
}
inline void Packet::set_allocated_player_snapshot(::PlayerSnap* player_snapshot) {
  delete player_snapshot_;
  player_snapshot_ = player_snapshot;
  if (player_snapshot) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:Packet.player_snapshot)
}

// .ServerSnap server_snapshot = 3;
inline bool Packet::has_server_snapshot() const {
  return this != internal_default_instance() && server_snapshot_ != NULL;
}
inline void Packet::clear_server_snapshot() {
  if (GetArenaNoVirtual() == NULL && server_snapshot_ != NULL) delete server_snapshot_;
  server_snapshot_ = NULL;
}
inline const ::ServerSnap& Packet::server_snapshot() const {
  const ::ServerSnap* p = server_snapshot_;
  // @@protoc_insertion_point(field_get:Packet.server_snapshot)
  return p != NULL ? *p : *reinterpret_cast<const ::ServerSnap*>(
      &::_ServerSnap_default_instance_);
}
inline ::ServerSnap* Packet::mutable_server_snapshot() {
  
  if (server_snapshot_ == NULL) {
    server_snapshot_ = new ::ServerSnap;
  }
  // @@protoc_insertion_point(field_mutable:Packet.server_snapshot)
  return server_snapshot_;
}
inline ::ServerSnap* Packet::release_server_snapshot() {
  // @@protoc_insertion_point(field_release:Packet.server_snapshot)
  
  ::ServerSnap* temp = server_snapshot_;
  server_snapshot_ = NULL;
  return temp;
}
inline void Packet::set_allocated_server_snapshot(::ServerSnap* server_snapshot) {
  delete server_snapshot_;
  server_snapshot_ = server_snapshot;
  if (server_snapshot) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:Packet.server_snapshot)
}

// .ConnectAck connect_ack = 4;
inline bool Packet::has_connect_ack() const {
  return this != internal_default_instance() && connect_ack_ != NULL;
}
inline void Packet::clear_connect_ack() {
  if (GetArenaNoVirtual() == NULL && connect_ack_ != NULL) delete connect_ack_;
  connect_ack_ = NULL;
}
inline const ::ConnectAck& Packet::connect_ack() const {
  const ::ConnectAck* p = connect_ack_;
  // @@protoc_insertion_point(field_get:Packet.connect_ack)
  return p != NULL ? *p : *reinterpret_cast<const ::ConnectAck*>(
      &::_ConnectAck_default_instance_);
}
inline ::ConnectAck* Packet::mutable_connect_ack() {
  
  if (connect_ack_ == NULL) {
    connect_ack_ = new ::ConnectAck;
  }
  // @@protoc_insertion_point(field_mutable:Packet.connect_ack)
  return connect_ack_;
}
inline ::ConnectAck* Packet::release_connect_ack() {
  // @@protoc_insertion_point(field_release:Packet.connect_ack)
  
  ::ConnectAck* temp = connect_ack_;
  connect_ack_ = NULL;
  return temp;
}
inline void Packet::set_allocated_connect_ack(::ConnectAck* connect_ack) {
  delete connect_ack_;
  connect_ack_ = connect_ack;
  if (connect_ack) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:Packet.connect_ack)
}

// -------------------------------------------------------------------

// ConnectAck

// int32 index = 1;
inline void ConnectAck::clear_index() {
  index_ = 0;
}
inline ::google::protobuf::int32 ConnectAck::index() const {
  // @@protoc_insertion_point(field_get:ConnectAck.index)
  return index_;
}
inline void ConnectAck::set_index(::google::protobuf::int32 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:ConnectAck.index)
}

// -------------------------------------------------------------------

// PlayerSnap

// float X = 1;
inline void PlayerSnap::clear_x() {
  x_ = 0;
}
inline float PlayerSnap::x() const {
  // @@protoc_insertion_point(field_get:PlayerSnap.X)
  return x_;
}
inline void PlayerSnap::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:PlayerSnap.X)
}

// float Y = 2;
inline void PlayerSnap::clear_y() {
  y_ = 0;
}
inline float PlayerSnap::y() const {
  // @@protoc_insertion_point(field_get:PlayerSnap.Y)
  return y_;
}
inline void PlayerSnap::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:PlayerSnap.Y)
}

// float Z = 3;
inline void PlayerSnap::clear_z() {
  z_ = 0;
}
inline float PlayerSnap::z() const {
  // @@protoc_insertion_point(field_get:PlayerSnap.Z)
  return z_;
}
inline void PlayerSnap::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:PlayerSnap.Z)
}

// float ViewX = 4;
inline void PlayerSnap::clear_viewx() {
  viewx_ = 0;
}
inline float PlayerSnap::viewx() const {
  // @@protoc_insertion_point(field_get:PlayerSnap.ViewX)
  return viewx_;
}
inline void PlayerSnap::set_viewx(float value) {
  
  viewx_ = value;
  // @@protoc_insertion_point(field_set:PlayerSnap.ViewX)
}

// float ViewY = 5;
inline void PlayerSnap::clear_viewy() {
  viewy_ = 0;
}
inline float PlayerSnap::viewy() const {
  // @@protoc_insertion_point(field_get:PlayerSnap.ViewY)
  return viewy_;
}
inline void PlayerSnap::set_viewy(float value) {
  
  viewy_ = value;
  // @@protoc_insertion_point(field_set:PlayerSnap.ViewY)
}

// bool Walk_forward = 6;
inline void PlayerSnap::clear_walk_forward() {
  walk_forward_ = false;
}
inline bool PlayerSnap::walk_forward() const {
  // @@protoc_insertion_point(field_get:PlayerSnap.Walk_forward)
  return walk_forward_;
}
inline void PlayerSnap::set_walk_forward(bool value) {
  
  walk_forward_ = value;
  // @@protoc_insertion_point(field_set:PlayerSnap.Walk_forward)
}

// bool Walk_backward = 7;
inline void PlayerSnap::clear_walk_backward() {
  walk_backward_ = false;
}
inline bool PlayerSnap::walk_backward() const {
  // @@protoc_insertion_point(field_get:PlayerSnap.Walk_backward)
  return walk_backward_;
}
inline void PlayerSnap::set_walk_backward(bool value) {
  
  walk_backward_ = value;
  // @@protoc_insertion_point(field_set:PlayerSnap.Walk_backward)
}

// bool Walk_left = 8;
inline void PlayerSnap::clear_walk_left() {
  walk_left_ = false;
}
inline bool PlayerSnap::walk_left() const {
  // @@protoc_insertion_point(field_get:PlayerSnap.Walk_left)
  return walk_left_;
}
inline void PlayerSnap::set_walk_left(bool value) {
  
  walk_left_ = value;
  // @@protoc_insertion_point(field_set:PlayerSnap.Walk_left)
}

// bool Walk_right = 9;
inline void PlayerSnap::clear_walk_right() {
  walk_right_ = false;
}
inline bool PlayerSnap::walk_right() const {
  // @@protoc_insertion_point(field_get:PlayerSnap.Walk_right)
  return walk_right_;
}
inline void PlayerSnap::set_walk_right(bool value) {
  
  walk_right_ = value;
  // @@protoc_insertion_point(field_set:PlayerSnap.Walk_right)
}

// bool Jump = 10;
inline void PlayerSnap::clear_jump() {
  jump_ = false;
}
inline bool PlayerSnap::jump() const {
  // @@protoc_insertion_point(field_get:PlayerSnap.Jump)
  return jump_;
}
inline void PlayerSnap::set_jump(bool value) {
  
  jump_ = value;
  // @@protoc_insertion_point(field_set:PlayerSnap.Jump)
}

// bool Crouch = 11;
inline void PlayerSnap::clear_crouch() {
  crouch_ = false;
}
inline bool PlayerSnap::crouch() const {
  // @@protoc_insertion_point(field_get:PlayerSnap.Crouch)
  return crouch_;
}
inline void PlayerSnap::set_crouch(bool value) {
  
  crouch_ = value;
  // @@protoc_insertion_point(field_set:PlayerSnap.Crouch)
}

// bool Fire = 12;
inline void PlayerSnap::clear_fire() {
  fire_ = false;
}
inline bool PlayerSnap::fire() const {
  // @@protoc_insertion_point(field_get:PlayerSnap.Fire)
  return fire_;
}
inline void PlayerSnap::set_fire(bool value) {
  
  fire_ = value;
  // @@protoc_insertion_point(field_set:PlayerSnap.Fire)
}

// bool Fire_hold = 13;
inline void PlayerSnap::clear_fire_hold() {
  fire_hold_ = false;
}
inline bool PlayerSnap::fire_hold() const {
  // @@protoc_insertion_point(field_get:PlayerSnap.Fire_hold)
  return fire_hold_;
}
inline void PlayerSnap::set_fire_hold(bool value) {
  
  fire_hold_ = value;
  // @@protoc_insertion_point(field_set:PlayerSnap.Fire_hold)
}

// float Fire_hold_time = 14;
inline void PlayerSnap::clear_fire_hold_time() {
  fire_hold_time_ = 0;
}
inline float PlayerSnap::fire_hold_time() const {
  // @@protoc_insertion_point(field_get:PlayerSnap.Fire_hold_time)
  return fire_hold_time_;
}
inline void PlayerSnap::set_fire_hold_time(float value) {
  
  fire_hold_time_ = value;
  // @@protoc_insertion_point(field_set:PlayerSnap.Fire_hold_time)
}

// bool Fire_release = 15;
inline void PlayerSnap::clear_fire_release() {
  fire_release_ = false;
}
inline bool PlayerSnap::fire_release() const {
  // @@protoc_insertion_point(field_get:PlayerSnap.Fire_release)
  return fire_release_;
}
inline void PlayerSnap::set_fire_release(bool value) {
  
  fire_release_ = value;
  // @@protoc_insertion_point(field_set:PlayerSnap.Fire_release)
}

// float Fire_release_time = 16;
inline void PlayerSnap::clear_fire_release_time() {
  fire_release_time_ = 0;
}
inline float PlayerSnap::fire_release_time() const {
  // @@protoc_insertion_point(field_get:PlayerSnap.Fire_release_time)
  return fire_release_time_;
}
inline void PlayerSnap::set_fire_release_time(float value) {
  
  fire_release_time_ = value;
  // @@protoc_insertion_point(field_set:PlayerSnap.Fire_release_time)
}

// int32 Weapon_switch = 17;
inline void PlayerSnap::clear_weapon_switch() {
  weapon_switch_ = 0;
}
inline ::google::protobuf::int32 PlayerSnap::weapon_switch() const {
  // @@protoc_insertion_point(field_get:PlayerSnap.Weapon_switch)
  return weapon_switch_;
}
inline void PlayerSnap::set_weapon_switch(::google::protobuf::int32 value) {
  
  weapon_switch_ = value;
  // @@protoc_insertion_point(field_set:PlayerSnap.Weapon_switch)
}

// float Weapon_switch_time = 18;
inline void PlayerSnap::clear_weapon_switch_time() {
  weapon_switch_time_ = 0;
}
inline float PlayerSnap::weapon_switch_time() const {
  // @@protoc_insertion_point(field_get:PlayerSnap.Weapon_switch_time)
  return weapon_switch_time_;
}
inline void PlayerSnap::set_weapon_switch_time(float value) {
  
  weapon_switch_time_ = value;
  // @@protoc_insertion_point(field_set:PlayerSnap.Weapon_switch_time)
}

// int32 Weapon_slot = 19;
inline void PlayerSnap::clear_weapon_slot() {
  weapon_slot_ = 0;
}
inline ::google::protobuf::int32 PlayerSnap::weapon_slot() const {
  // @@protoc_insertion_point(field_get:PlayerSnap.Weapon_slot)
  return weapon_slot_;
}
inline void PlayerSnap::set_weapon_slot(::google::protobuf::int32 value) {
  
  weapon_slot_ = value;
  // @@protoc_insertion_point(field_set:PlayerSnap.Weapon_slot)
}

// int32 packet_sequence = 20;
inline void PlayerSnap::clear_packet_sequence() {
  packet_sequence_ = 0;
}
inline ::google::protobuf::int32 PlayerSnap::packet_sequence() const {
  // @@protoc_insertion_point(field_get:PlayerSnap.packet_sequence)
  return packet_sequence_;
}
inline void PlayerSnap::set_packet_sequence(::google::protobuf::int32 value) {
  
  packet_sequence_ = value;
  // @@protoc_insertion_point(field_set:PlayerSnap.packet_sequence)
}

// -------------------------------------------------------------------

// ServerSnap_PlayerData_WeaponWheel

// bool bWarClub = 1;
inline void ServerSnap_PlayerData_WeaponWheel::clear_bwarclub() {
  bwarclub_ = false;
}
inline bool ServerSnap_PlayerData_WeaponWheel::bwarclub() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.bWarClub)
  return bwarclub_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_bwarclub(bool value) {
  
  bwarclub_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.bWarClub)
}

// bool bHas_Bow = 2;
inline void ServerSnap_PlayerData_WeaponWheel::clear_bhas_bow() {
  bhas_bow_ = false;
}
inline bool ServerSnap_PlayerData_WeaponWheel::bhas_bow() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.bHas_Bow)
  return bhas_bow_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_bhas_bow(bool value) {
  
  bhas_bow_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.bHas_Bow)
}

// int32 bow_Normal_Ammo = 3;
inline void ServerSnap_PlayerData_WeaponWheel::clear_bow_normal_ammo() {
  bow_normal_ammo_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::bow_normal_ammo() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.bow_Normal_Ammo)
  return bow_normal_ammo_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_bow_normal_ammo(::google::protobuf::int32 value) {
  
  bow_normal_ammo_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.bow_Normal_Ammo)
}

// int32 bow_Explosive_Ammo = 4;
inline void ServerSnap_PlayerData_WeaponWheel::clear_bow_explosive_ammo() {
  bow_explosive_ammo_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::bow_explosive_ammo() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.bow_Explosive_Ammo)
  return bow_explosive_ammo_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_bow_explosive_ammo(::google::protobuf::int32 value) {
  
  bow_explosive_ammo_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.bow_Explosive_Ammo)
}

// int32 bow_Poison_Ammo = 5;
inline void ServerSnap_PlayerData_WeaponWheel::clear_bow_poison_ammo() {
  bow_poison_ammo_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::bow_poison_ammo() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.bow_Poison_Ammo)
  return bow_poison_ammo_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_bow_poison_ammo(::google::protobuf::int32 value) {
  
  bow_poison_ammo_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.bow_Poison_Ammo)
}

// bool bHas_TekBow = 6;
inline void ServerSnap_PlayerData_WeaponWheel::clear_bhas_tekbow() {
  bhas_tekbow_ = false;
}
inline bool ServerSnap_PlayerData_WeaponWheel::bhas_tekbow() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.bHas_TekBow)
  return bhas_tekbow_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_bhas_tekbow(bool value) {
  
  bhas_tekbow_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.bHas_TekBow)
}

// int32 TekBow_NormalAmmo = 7;
inline void ServerSnap_PlayerData_WeaponWheel::clear_tekbow_normalammo() {
  tekbow_normalammo_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::tekbow_normalammo() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.TekBow_NormalAmmo)
  return tekbow_normalammo_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_tekbow_normalammo(::google::protobuf::int32 value) {
  
  tekbow_normalammo_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.TekBow_NormalAmmo)
}

// int32 TekBow_ExplosiveAmmo = 8;
inline void ServerSnap_PlayerData_WeaponWheel::clear_tekbow_explosiveammo() {
  tekbow_explosiveammo_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::tekbow_explosiveammo() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.TekBow_ExplosiveAmmo)
  return tekbow_explosiveammo_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_tekbow_explosiveammo(::google::protobuf::int32 value) {
  
  tekbow_explosiveammo_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.TekBow_ExplosiveAmmo)
}

// int32 TekBow_PosionAmmo = 9;
inline void ServerSnap_PlayerData_WeaponWheel::clear_tekbow_posionammo() {
  tekbow_posionammo_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::tekbow_posionammo() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.TekBow_PosionAmmo)
  return tekbow_posionammo_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_tekbow_posionammo(::google::protobuf::int32 value) {
  
  tekbow_posionammo_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.TekBow_PosionAmmo)
}

// bool bHas_SpikeGrenade = 10;
inline void ServerSnap_PlayerData_WeaponWheel::clear_bhas_spikegrenade() {
  bhas_spikegrenade_ = false;
}
inline bool ServerSnap_PlayerData_WeaponWheel::bhas_spikegrenade() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.bHas_SpikeGrenade)
  return bhas_spikegrenade_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_bhas_spikegrenade(bool value) {
  
  bhas_spikegrenade_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.bHas_SpikeGrenade)
}

// int32 SpikeGrenade_Ammo = 11;
inline void ServerSnap_PlayerData_WeaponWheel::clear_spikegrenade_ammo() {
  spikegrenade_ammo_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::spikegrenade_ammo() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.SpikeGrenade_Ammo)
  return spikegrenade_ammo_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_spikegrenade_ammo(::google::protobuf::int32 value) {
  
  spikegrenade_ammo_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.SpikeGrenade_Ammo)
}

// bool bHas_Pistol = 12;
inline void ServerSnap_PlayerData_WeaponWheel::clear_bhas_pistol() {
  bhas_pistol_ = false;
}
inline bool ServerSnap_PlayerData_WeaponWheel::bhas_pistol() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.bHas_Pistol)
  return bhas_pistol_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_bhas_pistol(bool value) {
  
  bhas_pistol_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.bHas_Pistol)
}

// int32 Pistol_Ammo = 13;
inline void ServerSnap_PlayerData_WeaponWheel::clear_pistol_ammo() {
  pistol_ammo_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::pistol_ammo() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.Pistol_Ammo)
  return pistol_ammo_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_pistol_ammo(::google::protobuf::int32 value) {
  
  pistol_ammo_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.Pistol_Ammo)
}

// bool bHas_ShotGun = 14;
inline void ServerSnap_PlayerData_WeaponWheel::clear_bhas_shotgun() {
  bhas_shotgun_ = false;
}
inline bool ServerSnap_PlayerData_WeaponWheel::bhas_shotgun() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.bHas_ShotGun)
  return bhas_shotgun_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_bhas_shotgun(bool value) {
  
  bhas_shotgun_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.bHas_ShotGun)
}

// int32 ShotGun_Ammo = 15;
inline void ServerSnap_PlayerData_WeaponWheel::clear_shotgun_ammo() {
  shotgun_ammo_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::shotgun_ammo() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.ShotGun_Ammo)
  return shotgun_ammo_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_shotgun_ammo(::google::protobuf::int32 value) {
  
  shotgun_ammo_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.ShotGun_Ammo)
}

// bool bHas_Flecheete = 16;
inline void ServerSnap_PlayerData_WeaponWheel::clear_bhas_flecheete() {
  bhas_flecheete_ = false;
}
inline bool ServerSnap_PlayerData_WeaponWheel::bhas_flecheete() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.bHas_Flecheete)
  return bhas_flecheete_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_bhas_flecheete(bool value) {
  
  bhas_flecheete_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.bHas_Flecheete)
}

// int32 Fleechete_Ammo = 17;
inline void ServerSnap_PlayerData_WeaponWheel::clear_fleechete_ammo() {
  fleechete_ammo_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::fleechete_ammo() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.Fleechete_Ammo)
  return fleechete_ammo_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_fleechete_ammo(::google::protobuf::int32 value) {
  
  fleechete_ammo_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.Fleechete_Ammo)
}

// int32 MiniGun_Ammo = 18;
inline void ServerSnap_PlayerData_WeaponWheel::clear_minigun_ammo() {
  minigun_ammo_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::minigun_ammo() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.MiniGun_Ammo)
  return minigun_ammo_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_minigun_ammo(::google::protobuf::int32 value) {
  
  minigun_ammo_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.MiniGun_Ammo)
}

// bool bHas_RocketLauncher = 19;
inline void ServerSnap_PlayerData_WeaponWheel::clear_bhas_rocketlauncher() {
  bhas_rocketlauncher_ = false;
}
inline bool ServerSnap_PlayerData_WeaponWheel::bhas_rocketlauncher() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.bHas_RocketLauncher)
  return bhas_rocketlauncher_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_bhas_rocketlauncher(bool value) {
  
  bhas_rocketlauncher_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.bHas_RocketLauncher)
}

// int32 Rocket_Ammo1 = 20;
inline void ServerSnap_PlayerData_WeaponWheel::clear_rocket_ammo1() {
  rocket_ammo1_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::rocket_ammo1() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.Rocket_Ammo1)
  return rocket_ammo1_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_rocket_ammo1(::google::protobuf::int32 value) {
  
  rocket_ammo1_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.Rocket_Ammo1)
}

// int32 Rocket_Ammo2 = 21;
inline void ServerSnap_PlayerData_WeaponWheel::clear_rocket_ammo2() {
  rocket_ammo2_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::rocket_ammo2() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.Rocket_Ammo2)
  return rocket_ammo2_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_rocket_ammo2(::google::protobuf::int32 value) {
  
  rocket_ammo2_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.Rocket_Ammo2)
}

// int32 Rocket_Ammo3 = 22;
inline void ServerSnap_PlayerData_WeaponWheel::clear_rocket_ammo3() {
  rocket_ammo3_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::rocket_ammo3() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.Rocket_Ammo3)
  return rocket_ammo3_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_rocket_ammo3(::google::protobuf::int32 value) {
  
  rocket_ammo3_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.Rocket_Ammo3)
}

// bool bHas_PlasmaCannon = 23;
inline void ServerSnap_PlayerData_WeaponWheel::clear_bhas_plasmacannon() {
  bhas_plasmacannon_ = false;
}
inline bool ServerSnap_PlayerData_WeaponWheel::bhas_plasmacannon() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.bHas_PlasmaCannon)
  return bhas_plasmacannon_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_bhas_plasmacannon(bool value) {
  
  bhas_plasmacannon_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.bHas_PlasmaCannon)
}

// int32 Plasma_Ammo1 = 24;
inline void ServerSnap_PlayerData_WeaponWheel::clear_plasma_ammo1() {
  plasma_ammo1_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::plasma_ammo1() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.Plasma_Ammo1)
  return plasma_ammo1_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_plasma_ammo1(::google::protobuf::int32 value) {
  
  plasma_ammo1_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.Plasma_Ammo1)
}

// int32 Plasma_Ammo2 = 25;
inline void ServerSnap_PlayerData_WeaponWheel::clear_plasma_ammo2() {
  plasma_ammo2_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::plasma_ammo2() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.Plasma_Ammo2)
  return plasma_ammo2_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_plasma_ammo2(::google::protobuf::int32 value) {
  
  plasma_ammo2_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.Plasma_Ammo2)
}

// int32 Plasma_Ammo3 = 26;
inline void ServerSnap_PlayerData_WeaponWheel::clear_plasma_ammo3() {
  plasma_ammo3_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::plasma_ammo3() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.Plasma_Ammo3)
  return plasma_ammo3_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_plasma_ammo3(::google::protobuf::int32 value) {
  
  plasma_ammo3_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.Plasma_Ammo3)
}

// bool bHas_FlameThrower = 27;
inline void ServerSnap_PlayerData_WeaponWheel::clear_bhas_flamethrower() {
  bhas_flamethrower_ = false;
}
inline bool ServerSnap_PlayerData_WeaponWheel::bhas_flamethrower() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.bHas_FlameThrower)
  return bhas_flamethrower_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_bhas_flamethrower(bool value) {
  
  bhas_flamethrower_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.bHas_FlameThrower)
}

// int32 FlameThrower_Ammo = 28;
inline void ServerSnap_PlayerData_WeaponWheel::clear_flamethrower_ammo() {
  flamethrower_ammo_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::flamethrower_ammo() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.FlameThrower_Ammo)
  return flamethrower_ammo_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_flamethrower_ammo(::google::protobuf::int32 value) {
  
  flamethrower_ammo_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.FlameThrower_Ammo)
}

// bool bHas_SpiderMine = 29;
inline void ServerSnap_PlayerData_WeaponWheel::clear_bhas_spidermine() {
  bhas_spidermine_ = false;
}
inline bool ServerSnap_PlayerData_WeaponWheel::bhas_spidermine() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.bHas_SpiderMine)
  return bhas_spidermine_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_bhas_spidermine(bool value) {
  
  bhas_spidermine_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.bHas_SpiderMine)
}

// int32 SpiderMine_Ammo = 30;
inline void ServerSnap_PlayerData_WeaponWheel::clear_spidermine_ammo() {
  spidermine_ammo_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::spidermine_ammo() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.SpiderMine_Ammo)
  return spidermine_ammo_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_spidermine_ammo(::google::protobuf::int32 value) {
  
  spidermine_ammo_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.SpiderMine_Ammo)
}

// bool bHas_GravityGun = 31;
inline void ServerSnap_PlayerData_WeaponWheel::clear_bhas_gravitygun() {
  bhas_gravitygun_ = false;
}
inline bool ServerSnap_PlayerData_WeaponWheel::bhas_gravitygun() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.bHas_GravityGun)
  return bhas_gravitygun_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_bhas_gravitygun(bool value) {
  
  bhas_gravitygun_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.bHas_GravityGun)
}

// int32 GravityGun_Ammo = 32;
inline void ServerSnap_PlayerData_WeaponWheel::clear_gravitygun_ammo() {
  gravitygun_ammo_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::gravitygun_ammo() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.GravityGun_Ammo)
  return gravitygun_ammo_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_gravitygun_ammo(::google::protobuf::int32 value) {
  
  gravitygun_ammo_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.GravityGun_Ammo)
}

// int32 GravityGun_Ammo2 = 33;
inline void ServerSnap_PlayerData_WeaponWheel::clear_gravitygun_ammo2() {
  gravitygun_ammo2_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::gravitygun_ammo2() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.GravityGun_Ammo2)
  return gravitygun_ammo2_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_gravitygun_ammo2(::google::protobuf::int32 value) {
  
  gravitygun_ammo2_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.GravityGun_Ammo2)
}

// bool bHas_DarkMatter = 34;
inline void ServerSnap_PlayerData_WeaponWheel::clear_bhas_darkmatter() {
  bhas_darkmatter_ = false;
}
inline bool ServerSnap_PlayerData_WeaponWheel::bhas_darkmatter() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.bHas_DarkMatter)
  return bhas_darkmatter_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_bhas_darkmatter(bool value) {
  
  bhas_darkmatter_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.bHas_DarkMatter)
}

// int32 DarkMatter_Ammo = 35;
inline void ServerSnap_PlayerData_WeaponWheel::clear_darkmatter_ammo() {
  darkmatter_ammo_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::darkmatter_ammo() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.DarkMatter_Ammo)
  return darkmatter_ammo_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_darkmatter_ammo(::google::protobuf::int32 value) {
  
  darkmatter_ammo_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.DarkMatter_Ammo)
}

// bool bHas_CrossBow = 36;
inline void ServerSnap_PlayerData_WeaponWheel::clear_bhas_crossbow() {
  bhas_crossbow_ = false;
}
inline bool ServerSnap_PlayerData_WeaponWheel::bhas_crossbow() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.bHas_CrossBow)
  return bhas_crossbow_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_bhas_crossbow(bool value) {
  
  bhas_crossbow_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.bHas_CrossBow)
}

// int32 CrossBow_Normal_Ammo = 37;
inline void ServerSnap_PlayerData_WeaponWheel::clear_crossbow_normal_ammo() {
  crossbow_normal_ammo_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::crossbow_normal_ammo() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.CrossBow_Normal_Ammo)
  return crossbow_normal_ammo_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_crossbow_normal_ammo(::google::protobuf::int32 value) {
  
  crossbow_normal_ammo_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.CrossBow_Normal_Ammo)
}

// int32 CrossBow_Explosive_Ammo = 38;
inline void ServerSnap_PlayerData_WeaponWheel::clear_crossbow_explosive_ammo() {
  crossbow_explosive_ammo_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::crossbow_explosive_ammo() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.CrossBow_Explosive_Ammo)
  return crossbow_explosive_ammo_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_crossbow_explosive_ammo(::google::protobuf::int32 value) {
  
  crossbow_explosive_ammo_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.CrossBow_Explosive_Ammo)
}

// int32 CrossBow_Poison_Ammo = 39;
inline void ServerSnap_PlayerData_WeaponWheel::clear_crossbow_poison_ammo() {
  crossbow_poison_ammo_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData_WeaponWheel::crossbow_poison_ammo() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.WeaponWheel.CrossBow_Poison_Ammo)
  return crossbow_poison_ammo_;
}
inline void ServerSnap_PlayerData_WeaponWheel::set_crossbow_poison_ammo(::google::protobuf::int32 value) {
  
  crossbow_poison_ammo_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.WeaponWheel.CrossBow_Poison_Ammo)
}

// -------------------------------------------------------------------

// ServerSnap_PlayerData

// float X = 1;
inline void ServerSnap_PlayerData::clear_x() {
  x_ = 0;
}
inline float ServerSnap_PlayerData::x() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.X)
  return x_;
}
inline void ServerSnap_PlayerData::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.X)
}

// float Y = 2;
inline void ServerSnap_PlayerData::clear_y() {
  y_ = 0;
}
inline float ServerSnap_PlayerData::y() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.Y)
  return y_;
}
inline void ServerSnap_PlayerData::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.Y)
}

// float Z = 3;
inline void ServerSnap_PlayerData::clear_z() {
  z_ = 0;
}
inline float ServerSnap_PlayerData::z() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.Z)
  return z_;
}
inline void ServerSnap_PlayerData::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.Z)
}

// float ViewX = 4;
inline void ServerSnap_PlayerData::clear_viewx() {
  viewx_ = 0;
}
inline float ServerSnap_PlayerData::viewx() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.ViewX)
  return viewx_;
}
inline void ServerSnap_PlayerData::set_viewx(float value) {
  
  viewx_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.ViewX)
}

// float ViewY = 5;
inline void ServerSnap_PlayerData::clear_viewy() {
  viewy_ = 0;
}
inline float ServerSnap_PlayerData::viewy() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.ViewY)
  return viewy_;
}
inline void ServerSnap_PlayerData::set_viewy(float value) {
  
  viewy_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.ViewY)
}

// bool Walk_forward = 6;
inline void ServerSnap_PlayerData::clear_walk_forward() {
  walk_forward_ = false;
}
inline bool ServerSnap_PlayerData::walk_forward() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.Walk_forward)
  return walk_forward_;
}
inline void ServerSnap_PlayerData::set_walk_forward(bool value) {
  
  walk_forward_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.Walk_forward)
}

// bool Walk_backward = 7;
inline void ServerSnap_PlayerData::clear_walk_backward() {
  walk_backward_ = false;
}
inline bool ServerSnap_PlayerData::walk_backward() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.Walk_backward)
  return walk_backward_;
}
inline void ServerSnap_PlayerData::set_walk_backward(bool value) {
  
  walk_backward_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.Walk_backward)
}

// bool Walk_left = 8;
inline void ServerSnap_PlayerData::clear_walk_left() {
  walk_left_ = false;
}
inline bool ServerSnap_PlayerData::walk_left() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.Walk_left)
  return walk_left_;
}
inline void ServerSnap_PlayerData::set_walk_left(bool value) {
  
  walk_left_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.Walk_left)
}

// bool Walk_right = 9;
inline void ServerSnap_PlayerData::clear_walk_right() {
  walk_right_ = false;
}
inline bool ServerSnap_PlayerData::walk_right() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.Walk_right)
  return walk_right_;
}
inline void ServerSnap_PlayerData::set_walk_right(bool value) {
  
  walk_right_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.Walk_right)
}

// bool Jump = 10;
inline void ServerSnap_PlayerData::clear_jump() {
  jump_ = false;
}
inline bool ServerSnap_PlayerData::jump() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.Jump)
  return jump_;
}
inline void ServerSnap_PlayerData::set_jump(bool value) {
  
  jump_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.Jump)
}

// bool Crouch = 11;
inline void ServerSnap_PlayerData::clear_crouch() {
  crouch_ = false;
}
inline bool ServerSnap_PlayerData::crouch() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.Crouch)
  return crouch_;
}
inline void ServerSnap_PlayerData::set_crouch(bool value) {
  
  crouch_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.Crouch)
}

// bool Fire = 12;
inline void ServerSnap_PlayerData::clear_fire() {
  fire_ = false;
}
inline bool ServerSnap_PlayerData::fire() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.Fire)
  return fire_;
}
inline void ServerSnap_PlayerData::set_fire(bool value) {
  
  fire_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.Fire)
}

// bool Fire_hold = 13;
inline void ServerSnap_PlayerData::clear_fire_hold() {
  fire_hold_ = false;
}
inline bool ServerSnap_PlayerData::fire_hold() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.Fire_hold)
  return fire_hold_;
}
inline void ServerSnap_PlayerData::set_fire_hold(bool value) {
  
  fire_hold_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.Fire_hold)
}

// float Fire_hold_time = 14;
inline void ServerSnap_PlayerData::clear_fire_hold_time() {
  fire_hold_time_ = 0;
}
inline float ServerSnap_PlayerData::fire_hold_time() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.Fire_hold_time)
  return fire_hold_time_;
}
inline void ServerSnap_PlayerData::set_fire_hold_time(float value) {
  
  fire_hold_time_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.Fire_hold_time)
}

// bool Fire_release = 15;
inline void ServerSnap_PlayerData::clear_fire_release() {
  fire_release_ = false;
}
inline bool ServerSnap_PlayerData::fire_release() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.Fire_release)
  return fire_release_;
}
inline void ServerSnap_PlayerData::set_fire_release(bool value) {
  
  fire_release_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.Fire_release)
}

// float Fire_release_time = 16;
inline void ServerSnap_PlayerData::clear_fire_release_time() {
  fire_release_time_ = 0;
}
inline float ServerSnap_PlayerData::fire_release_time() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.Fire_release_time)
  return fire_release_time_;
}
inline void ServerSnap_PlayerData::set_fire_release_time(float value) {
  
  fire_release_time_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.Fire_release_time)
}

// float Max_health = 17;
inline void ServerSnap_PlayerData::clear_max_health() {
  max_health_ = 0;
}
inline float ServerSnap_PlayerData::max_health() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.Max_health)
  return max_health_;
}
inline void ServerSnap_PlayerData::set_max_health(float value) {
  
  max_health_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.Max_health)
}

// float Current_health = 18;
inline void ServerSnap_PlayerData::clear_current_health() {
  current_health_ = 0;
}
inline float ServerSnap_PlayerData::current_health() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.Current_health)
  return current_health_;
}
inline void ServerSnap_PlayerData::set_current_health(float value) {
  
  current_health_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.Current_health)
}

// int32 Weapon_switch = 19;
inline void ServerSnap_PlayerData::clear_weapon_switch() {
  weapon_switch_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData::weapon_switch() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.Weapon_switch)
  return weapon_switch_;
}
inline void ServerSnap_PlayerData::set_weapon_switch(::google::protobuf::int32 value) {
  
  weapon_switch_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.Weapon_switch)
}

// float Weapon_switch_time = 20;
inline void ServerSnap_PlayerData::clear_weapon_switch_time() {
  weapon_switch_time_ = 0;
}
inline float ServerSnap_PlayerData::weapon_switch_time() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.Weapon_switch_time)
  return weapon_switch_time_;
}
inline void ServerSnap_PlayerData::set_weapon_switch_time(float value) {
  
  weapon_switch_time_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.Weapon_switch_time)
}

// int32 Weapon_slot = 21;
inline void ServerSnap_PlayerData::clear_weapon_slot() {
  weapon_slot_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData::weapon_slot() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.Weapon_slot)
  return weapon_slot_;
}
inline void ServerSnap_PlayerData::set_weapon_slot(::google::protobuf::int32 value) {
  
  weapon_slot_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.Weapon_slot)
}

// .ServerSnap.PlayerData.WeaponWheel weapons = 22;
inline bool ServerSnap_PlayerData::has_weapons() const {
  return this != internal_default_instance() && weapons_ != NULL;
}
inline void ServerSnap_PlayerData::clear_weapons() {
  if (GetArenaNoVirtual() == NULL && weapons_ != NULL) delete weapons_;
  weapons_ = NULL;
}
inline const ::ServerSnap_PlayerData_WeaponWheel& ServerSnap_PlayerData::weapons() const {
  const ::ServerSnap_PlayerData_WeaponWheel* p = weapons_;
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.weapons)
  return p != NULL ? *p : *reinterpret_cast<const ::ServerSnap_PlayerData_WeaponWheel*>(
      &::_ServerSnap_PlayerData_WeaponWheel_default_instance_);
}
inline ::ServerSnap_PlayerData_WeaponWheel* ServerSnap_PlayerData::mutable_weapons() {
  
  if (weapons_ == NULL) {
    weapons_ = new ::ServerSnap_PlayerData_WeaponWheel;
  }
  // @@protoc_insertion_point(field_mutable:ServerSnap.PlayerData.weapons)
  return weapons_;
}
inline ::ServerSnap_PlayerData_WeaponWheel* ServerSnap_PlayerData::release_weapons() {
  // @@protoc_insertion_point(field_release:ServerSnap.PlayerData.weapons)
  
  ::ServerSnap_PlayerData_WeaponWheel* temp = weapons_;
  weapons_ = NULL;
  return temp;
}
inline void ServerSnap_PlayerData::set_allocated_weapons(::ServerSnap_PlayerData_WeaponWheel* weapons) {
  delete weapons_;
  weapons_ = weapons;
  if (weapons) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:ServerSnap.PlayerData.weapons)
}

// int32 index = 23;
inline void ServerSnap_PlayerData::clear_index() {
  index_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData::index() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.index)
  return index_;
}
inline void ServerSnap_PlayerData::set_index(::google::protobuf::int32 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.index)
}

// int32 death_type = 24;
inline void ServerSnap_PlayerData::clear_death_type() {
  death_type_ = 0;
}
inline ::google::protobuf::int32 ServerSnap_PlayerData::death_type() const {
  // @@protoc_insertion_point(field_get:ServerSnap.PlayerData.death_type)
  return death_type_;
}
inline void ServerSnap_PlayerData::set_death_type(::google::protobuf::int32 value) {
  
  death_type_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.PlayerData.death_type)
}

// -------------------------------------------------------------------

// ServerSnap

// repeated .ServerSnap.PlayerData player = 1;
inline int ServerSnap::player_size() const {
  return player_.size();
}
inline void ServerSnap::clear_player() {
  player_.Clear();
}
inline const ::ServerSnap_PlayerData& ServerSnap::player(int index) const {
  // @@protoc_insertion_point(field_get:ServerSnap.player)
  return player_.Get(index);
}
inline ::ServerSnap_PlayerData* ServerSnap::mutable_player(int index) {
  // @@protoc_insertion_point(field_mutable:ServerSnap.player)
  return player_.Mutable(index);
}
inline ::ServerSnap_PlayerData* ServerSnap::add_player() {
  // @@protoc_insertion_point(field_add:ServerSnap.player)
  return player_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ServerSnap_PlayerData >*
ServerSnap::mutable_player() {
  // @@protoc_insertion_point(field_mutable_list:ServerSnap.player)
  return &player_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ServerSnap_PlayerData >&
ServerSnap::player() const {
  // @@protoc_insertion_point(field_list:ServerSnap.player)
  return player_;
}

// int32 packet_sequence = 2;
inline void ServerSnap::clear_packet_sequence() {
  packet_sequence_ = 0;
}
inline ::google::protobuf::int32 ServerSnap::packet_sequence() const {
  // @@protoc_insertion_point(field_get:ServerSnap.packet_sequence)
  return packet_sequence_;
}
inline void ServerSnap::set_packet_sequence(::google::protobuf::int32 value) {
  
  packet_sequence_ = value;
  // @@protoc_insertion_point(field_set:ServerSnap.packet_sequence)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Packet_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Packet_Type>() {
  return ::Packet_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_t4mp_2eproto__INCLUDED
